# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

usable <- function(x1, x2, delta) {
    .Call('_wCI_usable', PACKAGE = 'wCI', x1, x2, delta)
}

usableHard <- function(x1, x2, delta) {
    .Call('_wCI_usableHard', PACKAGE = 'wCI', x1, x2, delta)
}

concordanceIndex_modified_helper <- function(x, y, deltaX, deltaY, alpha, outx, alternative, logicOp) {
    .Call('_wCI_concordanceIndex_modified_helper', PACKAGE = 'wCI', x, y, deltaX, deltaY, alpha, outx, alternative, logicOp)
}

kernel_gaussian_C <- function(x, m, s) {
    .Call('_wCI_kernel_gaussian_C', PACKAGE = 'wCI', x, m, s)
}

kernel_laplace_C <- function(x, m, b) {
    .Call('_wCI_kernel_laplace_C', PACKAGE = 'wCI', x, m, b)
}

concordanceIndex_modified_helper_weighted <- function(x, y, deltaX, deltaY, weightingFun_pred, weightingFun_obs, alpha, outx, alternative, logicOp, max_weight, max_weight_obs) {
    .Call('_wCI_concordanceIndex_modified_helper_weighted', PACKAGE = 'wCI', x, y, deltaX, deltaY, weightingFun_pred, weightingFun_obs, alpha, outx, alternative, logicOp, max_weight, max_weight_obs)
}

rCIPermC <- function(pin_x, pin_y, pobsCI, pR, pB, pn, pxties, pyties, pseed) {
    .Call('_wCI_rCIPermC', PACKAGE = 'wCI', pin_x, pin_y, pobsCI, pR, pB, pn, pxties, pyties, pseed)
}

