# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

concordanceIndex_modified_helper <- function(x, y, deltaX, deltaY, alpha, outx, alternative, logicOp) {
    .Call('_mCI_concordanceIndex_modified_helper', PACKAGE = 'mCI', x, y, deltaX, deltaY, alpha, outx, alternative, logicOp)
}

kernel_gaussian_C <- function(x, m, s) {
    .Call('_mCI_kernel_gaussian_C', PACKAGE = 'mCI', x, m, s)
}

kernel_laplace_C <- function(x, m, b) {
    .Call('_mCI_kernel_laplace_C', PACKAGE = 'mCI', x, m, b)
}

concordanceIndex_modified_helper_weighted <- function(x, y, deltaX, deltaY, weightingFun_pred, weightingFun_obs, alpha, outx, alternative, logicOp, max_weight, max_weight_obs, permute) {
    .Call('_mCI_concordanceIndex_modified_helper_weighted', PACKAGE = 'mCI', x, y, deltaX, deltaY, weightingFun_pred, weightingFun_obs, alpha, outx, alternative, logicOp, max_weight, max_weight_obs, permute)
}

concordanceIndex_modified_helper_parallel <- function(x, y, deltaX, deltaY, alpha, outx, alternative, logicOp) {
    .Call('_mCI_concordanceIndex_modified_helper_parallel', PACKAGE = 'mCI', x, y, deltaX, deltaY, alpha, outx, alternative, logicOp)
}

concordanceIndex_modified_AllinC <- function(x, y, deltaX, deltaY, alpha, outx, alternative, logicOp) {
    .Call('_mCI_concordanceIndex_modified_AllinC', PACKAGE = 'mCI', x, y, deltaX, deltaY, alpha, outx, alternative, logicOp)
}

shuffle <- function(array) {
    .Call('_mCI_shuffle', PACKAGE = 'mCI', array)
}

shuffleInt <- function(array) {
    .Call('_mCI_shuffleInt', PACKAGE = 'mCI', array)
}

permute_concordanceIndex_modified <- function(x, y, deltaX, deltaY, alpha, outx, permutations, nThreads) {
    .Call('_mCI_permute_concordanceIndex_modified', PACKAGE = 'mCI', x, y, deltaX, deltaY, alpha, outx, permutations, nThreads)
}

rcpp_hello <- function() {
    .Call('_mCI_rcpp_hello', PACKAGE = 'mCI')
}

